### ISSUE TITLE
.exe程序在上传完文件后会闪退

### ISSUE THREAD

**Issue by Annmun** [likaiqiang/chatgpt-document-reader#3]
api测试没问题，但是.exe程序在上传完文件后会闪退，尝试了PDF和txt文本，都是可编辑的状态，系统是win10中文家庭版 1909

**Comment by 0xZZSheep** [comment]
方便提供一下pdf与txt文本，以及上传的路径截图吗，我这边测试一下

**Comment by Annmun** [comment]
win10桌面路径，应该是PDF的文件名是中文，我改了文件名可以正常上传了。但是提问不了，我把PDF文件和提问截图给你。
[1.pdf](https://github.com/likaiqiang/chatgpt-pdf-reader/files/13917644/1.pdf)
![Uploading 微信截图_20240112180326.png…]()

**Comment by 0xZZSheep** [comment]
![image](https://github.com/likaiqiang/chatgpt-pdf-reader/assets/14501725/539dec3f-ddaf-468a-9f22-5d303dd4cec1)
我这边是可以的

**Comment by 0xZZSheep** [comment]
你的提问截图好像没有上传成功？我这边看不了

**Comment by Annmun** [comment]
可能是我的提问方式不对，现在好像可以了。
![1](https://github.com/likaiqiang/chatgpt-pdf-reader/assets/53742054/1c9dac64-4e95-4f03-bc0a-92628a639e80)

**Comment by 0xZZSheep** [comment]
我把prompt改成中文了，这样对中文问题友好一点，有什么问题尽管提
